//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


public class Problem4 {
    public static void main(String[] args){
        int sum = 0, num = 1, prev = 0, temp = 0;
        while(num < 4_000_000) {
            temp = num;
            num += prev;
            prev = temp;
            if(num % 2 == 0) {
                sum += num;
            }
        }
        System.out.println(sum);
    }
}